### ISSUE TITLE
[2020-10-19] [기능]#자동로그인 설정 후 비밀번호 변경 시 로그인 실패현상

### ISSUE THREAD

**Issue by nk915** [hanssak/OpenNetLink#15]
**App 정보**
branch 정보 : master
commit code : 304b3e2
Release 정보 :
컴파일 일자 : 2020.10.16
배포 일자 :
패치 일자 : 
설치 일자 :

**OS **
OS 버전 : 하모니카

**오류 현상**
자동로그인 설정 후 비밀번호 변경 시 로그인 시 이전 비밀번호로 자동 로그인 되어 로그인 되지않음
만약 수동으로 변경된 비밀번호 입력 시 정상 로그인됨

**예상 원인**
자동 로그인은 최근 변경된 사항이 업데이트 하지않는것으로 보여짐

**Comment by hanssak** [comment]
000c834 : 조치
패스워드 변경 시 자동로그인에도 변경된 패스워드 적용되도록 조치 완료 되었습니다.
