### ISSUE TITLE
[2020-10-19] [기능]# 환경설정 UI 유지되는 현상

### ISSUE THREAD

**Issue by nk915** [hanssak/OpenNetLink#16]
**App 정보**
branch 정보 : master
commit code : 304b3e2
Release 정보 :
컴파일 일자 : 2020.10.16
배포 일자 :
패치 일자 : 
설치 일자 :

**OS **
OS 버전 : 하모니카

**오류 현상**
환경설정 사이드바 켜진 상태로 로그아웃 시 설정창 유지되는 현상

**Comment by hanssak** [comment]
4bf968c 👍 
환경설정 사이드바 자동 변경되도록 조치되어 있습니다.
