### ISSUE TITLE
[2020-10-19] [기능]#PDF 미리보기 실패

### ISSUE THREAD

**Issue by pcbelej** [hanssak/OpenNetLink#17]
**App 정보**
branch 정보 : master
commit code : 771e29d
Release 정보 : 
컴파일 일자 : 2020.10.16
설치 일자 : 2020.10.16

**OS **
OS 버전 : Gooroom

**오류 현상**
PDF 미리보기 시도 시 내용이 제대로 표시되지 않음

**Comment by hanssak** [comment]
내부 확인 결과 특수문자가 포함된 경우에 발생되는것으로 확인됩니다.
이와 동일한 증상이신가요?

**Comment by pcbelej** [comment]
네 같은 것 같습니다.

**Comment by hanssak** [comment]
75f44b5: 버그 픽스 완료
