### ISSUE TITLE
[2020-10-21] [기능]# 간헐적으로 파일 전송되지 않음

### ISSUE THREAD

**Issue by nk915** [hanssak/OpenNetLink#21]
**App 정보**
branch 정보 : master
commit code : 2c53739
컴파일 일자 : 2020-10-19

**OS **
OS 버전 : 하모니카

**오류 현상**
간헐적으로 기가이상 파일 전송 시 전송되지 않음

**예상 원인**
같은 기가 파일도 간헐적으로 전송이 되지않아, 특정 상황이 있어보임

**Comment by hanssak** [comment]
수신하는 PC의 디스크용량은 충분하신가요?

**Comment by nk915** [comment]
송수신 디스크 용량이 부족하였습니다.
