### ISSUE TITLE
[2020-09-09] [기능]#이중화시 원본파일 위치 확인 기능 필요

### ISSUE THREAD

**Issue by kdy800** [hanssak/OpenNetLink#6]
**App 정보**
branch 정보 : master
commit code : 673c297
Release 정보 :
컴파일 일자 : 2020.09.09
배포 일자 :
패치 일자 : 
설치 일자 :

**OS **
OS 버전 : 구름
기타 APP 버전  :

**오류 현상**
결재자 결재건 파일 미리보기 수행시 간헐적으로 미리 보기 수행이 되지 않음

**예상 원인**
이중화로 인해 원본파일이 있는 서버와 결재자가 접속한 서버가 상이하여 문제가 발생한 것으로 파악 됨

**Comment by hanssak** [comment]
전송 파일 상세보기 요청에 대해 응답시, 망연계 서버엔진에서 해당 파일이 존재하는 서버의 IP 정보를 전달하도록 보완

**Comment by hanssak** [comment]
적용 및 시험 완료
