### ISSUE TITLE
[2020-09-23] [기능]# 비밀번호 변경 관련 이슈

### ISSUE THREAD

**Issue by nk915** [hanssak/OpenNetLink#8]
**App 정보**
branch 정보 : master 또는 branch명
commit code : 8133381
Release 정보 : OpenNetLink_v0.0.2+8133381
컴파일 일자 : 2020-09-18
배포 일자 : 
패치 일자 : 2020-09-22
설치 일자 : 2020-09-22

**OS **
OS 버전 : Tmax (Open Edition 3.1.0)
기타 APP 버전  : -

**오류 현상**
비밀번호 변경 시 현재 비밀번호와 변경 비밀번호가 동일 시 정상 진행

**예상 원인**
변경 시 체크 로직 필요

**Comment by hanssak** [comment]
7cbf279 
비밀번호 체크 시 기존과 같으면 알림메시지 팝업 구현 적용완료.
